FROM apache/airflow:2.10.3-python3.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt

COPY dags/ /opt/airflow/dags/
COPY scripts/ /opt/airflow/scripts/
COPY --chown=airflow:root .airflow/config/ /opt/airflow/config/
