appId: ma.rasd.maroc
productName: RASD-Maroc
copyright: Copyright © 2026

directories:
  output: "dist-electron"
  buildResources: "public"

files:
  - "../infra/electron/**/*"
  - "out/**/*"

win:
  target:
    - target: portable
      arch:
        - x64
  icon: "public/icon.png"
  artifactName: "${productName}-Portable-${version}.${ext}"

extraMetadata:
  main: "../infra/electron/main.js"
